spring.application.name=civicmind-backend

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/civicmind_db
spring.datasource.username=root
spring.datasource.password=root123


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
